import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNavigation() {
  return (
    <nav className="flex items-center p-4 pb-10 text-xl font-semibold justify-between">
      <div>Story Gallary</div>

      {/* <div>Sign in?</div> */}
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TopNavigation />
       {children}
      </body>
    </html>
  );
}
